### ISSUE TITLE
Example files for mutational spectra

### ISSUE THREAD

**Issue by edawson** [broadinstitute/getzlab-SignatureAnalyzer#11]
Hi,

   I can successfully run SignatureAnalyzer using a MAF file, but the same data transformed to a file of mutational spectra fails with the following error:  

```
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').
```

I am suspicious this is because my row names are mislabeled. Would it be possible to add an example spectra file so that I can make sure my input is in the proper format?

**Comment by shankara-a** [comment]
Sure we can add this; while we work on uploading an example, is it possible to provide the full stack trace?

**Comment by edawson** [comment]
Totally - here is my call and stack trace:
```
(base) ericco92@chorus-gpu-t4:~$ time signatureanalyzer -t spectra --hg_build hg19 -o rebc356_snps_enforced --del_ 500 --cosmic cosmic3 enforced.356.snp.tsv

---------------------------------------------------------
---------- S I G N A T U R E  A N A L Y Z E R  ----------
---------------------------------------------------------
   * Creating output dir at rebc356_snps_enforced
   * Using cosmic3 signatures
   * Saving ARD-NMF outputs to rebc356_snps_enforced/nmf_output.h5
   * Running ARD-NMF...
        0/9: nit= 6321 K=6      del=0.00000000
Traceback (most recent call last):
  File "/home/ericco92/anaconda3/bin/signatureanalyzer", line 10, in <module>
    sys.exit(main())
  File "/home/ericco92/anaconda3/lib/python3.7/site-packages/signatureanalyzer/__main__.py", line 186, in main
    **vars(args)
  File "/home/ericco92/anaconda3/lib/python3.7/site-packages/signatureanalyzer/signatureanalyzer.py", line 222, in run_spectra
    postprocess_msigs(res, cosmic_df, cosmic_index, cosmic)
  File "/home/ericco92/anaconda3/lib/python3.7/site-packages/signatureanalyzer/utils.py", line 334, in postprocess_msigs
    res["cosine"] = pd.DataFrame(cosine_similarity(X.T), index=X.columns, columns=X.columns).loc[ref_cols,nmf_cols]
  File "/home/ericco92/anaconda3/lib/python3.7/site-packages/sklearn/metrics/pairwise.py", line 1027, in cosine_similarity
    X, Y = check_pairwise_arrays(X, Y)
  File "/home/ericco92/anaconda3/lib/python3.7/site-packages/sklearn/metrics/pairwise.py", line 109, in check_pairwise_arrays
    estimator=estimator)
  File "/home/ericco92/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py", line 542, in check_array
    allow_nan=force_all_finite == 'allow-nan')
  File "/home/ericco92/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py", line 56, in _assert_all_finite
    raise ValueError(msg_err.format(type_err, X.dtype))
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').
Closing remaining open files:rebc356_snps_enforced/nmf_output.h5...done
```

**Comment by edawson** [comment]
Here are two lines from my input (with sample names removed):
```
MutationType
A[C>A]A 9   14  13  13  11  20  17  15  23  19  19  18  17  14  15  26  26  7   24  22  33  11  22  36  15  15  32  21  15  7   11  4   25  17  11  10  24  11  11  25  11  31  9   11  22  10  22  8   16  21  29  7   18  34  23  18  22  16  17  21  4   39  8   41  15  31  12  14  14  21  38  31  15  11  13  15  17  32  24  4   10  9   14  9   22  19  15  25  17  29  15  12  11  27  15  19  23  14  9   27  30  32  23  19  18  14  10  18  14  29  9   33  13  11  18  10  15  13  10  11  14  29  22  6   16  14  20  10  6   12  11  24  20  21  20  19  22  17  15  22  19  10  20  23  13  25  13  22  18  11  14  14  28  17  23  9   15  10  21  14  40  23  23  10  14  10  18  22  29  10  21  15  15  16  25  16  15  17  29  22  15  11  18  30  16  12  14  8   19  16  20  36  29  18  4   5   15  26  7   15  15  12  13  19  27  17  10  17  15  13  13  17  9   6   12  10  14  23  10  24  14  5   9   16  10  13  22  24  21  28  21  13  10  12  19  15  24  20  10  23  20  19  12  14  14  17  19  20  29  12  17  32  8   8   4   19  23  37  19  27  5   10  40  22  14  17  14  18  23  19  7   17  7   24  17  16  32  19  13  12  16  27  23  19  9   14  25  15  10  21  24  28  5   21  9   13  35  20  10  10  13  8   8   7   4   12  13  20  10  3   3   5   17  14  8   17  11  6   15  12  17  12  8   30  18  14  15  29  11  17  5   14  12  11  27  5   12  17  12  32  12  5   10  10  11  16  30  20  17  3   25  19  11  8   15  10   10   0 126  13
A[C>A]C 5   9   7   5   15  13  10  4   10  13  13  22  16  15  2   12  9   3   7   15  18  8   5   19  12  8   10  12  14  5   8   2   16  8   11  10  16  6   13  9   3   12  8   5   8   12  6   6   4   12  18  9   13  20  8   7   13  12  4   14  2   25  5   27  18  18  9   6   12  12  28  14  7   11  8   14  5   9   20  1   11  7   10  4   9   12  6   13  9   13  10  11  4   12  6   15  14  9   9   14  16  13  15  10  9   11  5   9   13  17  6   18  8   6   16  8   13  5   10  7   15  11  22  2   11  17  15  9   6   9   6   24  9   12  15  13  14  6   13  23  21  11  19  13  2   11  8   24  7   8   9   11  24  4   12  5   8   8   10  9   23  14  23  11  9   7   10  16  9   3   8   6   15  18  9   13  13  10  8   9   9   8   12  16  15  4   16  7   14  9   11  23  19  17  4   5   10  9   8   7   11  6   8   13  14  10  9   6   5   5   4   3   1   9   4   9   13  9   2   8   11  4   8   8   11  6   10  14  16  16  16  9   7   12  8   8   12  12  9   15  12  7   6   8   9   25  16  8   11  3   14  28  9   8   5   20  30  25  12  10  7   9   26  12  10  11  6   6   15  4   13  13  6   7   13  5   10  22  15  7   11  26  15  19  3   8   11  6   9   13  8   15  7   13  4   3   15  14  3   13  11  7   9   8   7   12  13  17  11  2   0   5   10  8   1   12  14  4   6   6   9   8   7   13  14  6   6   20  7   4   6   7   3   10  15  9   14  10  4   16  6   4   5   7   5   8   14  15  9   6   19  6   5   6   15  6    30   5 103   5
```

**Comment by shankara-a** [comment]
Hello!

Okay so I think I fixed the problem. 
Previously we expected the spectra index to have the following format:
> (REF)(ALT)(LEFT NT)(RIGHT NT)

while you (and Cosmic) catalogue the format with an arrow:
> (LEFT NT) (REF) > (ALT) (RIGHT NT)

If you update to the latest version (or clone the repo now) the updates should be there to take either format and map them properly to the cosmic signatures. Please let me know if this doesn't work!

I created a new file in docs that should explain all the inputs: https://github.com/broadinstitute/getzlab-SignatureAnalyzer/blob/master/docs/generating_mutational_spectra.md#single-base-substitution-sbs-spectra

Best,

Shankara

**Comment by shankara-a** [comment]
Closing issue - example files are added and documented.
