### ISSUE TITLE
cannot reindex from a duplicate axis 

### ISSUE THREAD

**Issue by njbernstein** [broadinstitute/getzlab-SignatureAnalyzer#19]
Job errored out while writing results:
```
/var/spool/slurm/d/job15231496/slurm_script: 8: /var/spool/slurm/d/job15231496/slurm_script: source: not found
/home/nicholas/miniconda3/envs/mutsig/lib/python3.6/site-packages/sklearn/ensemble/weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d
/home/nicholas/miniconda3/envs/mutsig/lib/python3.6/site-packages/signatureanalyzer/utils.py:459: H5pyDeprecationWarning: The default file mode will change to 'r' (read-only) in h5py 3.0. To suppress this warning, pass the mode you need to h5py.File(), or set the global default h5.get_config().default_file_mode, or set the environment variable H5PY_DEFAULT_READONLY=1. Available modes are: 'r', 'r+', 'w', 'w-'/'x', 'a'. See the docs for details.
  with h5py.File(file) as f:
Traceback (most recent call last):
  File "/home/nicholas/miniconda3/envs/mutsig/bin/signatureanalyzer", line 8, in <module>
    sys.exit(main())
  File "/home/nicholas/miniconda3/envs/mutsig/lib/python3.6/site-packages/signatureanalyzer/__main__.py", line 181, in main
    **vars(args)
  File "/home/nicholas/miniconda3/envs/mutsig/lib/python3.6/site-packages/signatureanalyzer/signatureanalyzer.py", line 143, in run_maf
    weighted_maf = assign_signature_weights_to_maf(maf, W, H)
  File "/home/nicholas/miniconda3/envs/mutsig/lib/python3.6/site-packages/signatureanalyzer/utils.py", line 442, in assign_signature_weights_to_maf
    signature_probabilities /= np.sum(signature_probabilities.values, axis=1, keepdims=True)
  File "/home/nicholas/miniconda3/envs/mutsig/lib/python3.6/site-packages/pandas/core/ops.py", line 894, in f
    result = method(self, other)
  File "/home/nicholas/miniconda3/envs/mutsig/lib/python3.6/site-packages/pandas/core/ops.py", line 1517, in f
    other = _align_method_FRAME(self, other, axis)
  File "/home/nicholas/miniconda3/envs/mutsig/lib/python3.6/site-packages/pandas/core/ops.py", line 1440, in _align_method_FRAME
    given_shape=right.shape))
ValueError: Unable to coerce to DataFrame, shape must be (3702, 3): given (3702, 1)
```
Ard NMF ran succesfully
```
---------------------------------------------------------
---------- S I G N A T U R E  A N A L Y Z E R  ----------
---------------------------------------------------------
   * Creating output dir at test_mutsig_filtered
   * Using GRCh38.p7.genome build
   * Using cosmic3_exome signatures
   * Loading spectra from test.maf
      * Mapping contexts: 3701 / 3702
   * Saving ARD-NMF outputs to test_mutsig_filtered/nmf_output.h5
   * Running ARD-NMF...
	0/9: nit= 1155 K=4  	del=0.00000000
	1/9: nit=  738 K=4  	del=0.00000000
	2/9: nit=  662 K=3  	del=0.00000000
	3/9: nit=  690 K=3  	del=0.00000000
	4/9: nit=  586 K=3  	del=0.00000000
	5/9: nit=  712 K=3  	del=0.00000000
	6/9: nit=  652 K=3  	del=0.00000000
	7/9: nit=  636 K=3  	del=0.00000000
	8/9: nit=  496 K=4  	del=0.00000000
	9/9: nit=  684 K=5  	del=0.00000000
   * Run 2 had lowest objective with mode (n=6) K = 3.
```

input:
```
	Hugo_Symbol	Tumor_Sample_Barcode	Chromosome	Start_Position	Reference_Allele	Tumor_Seq_Allele2	Variant_Type
358374	ATG4A	5369813	X	108091840	C	A	SNP
358407	TEX101	3924644	19	43416479	C	A	SNP
358498	NME2	4396053	17	51168277	C	A	SNP
358759	ATPAF2	3924644	17	18021143	G	T	SNP
358783	C2CD5	4396053	12	22515087	G	T	SNP
358811	CD52	3375285	1	26320200	C	A	SNP
358914	SH3BGRL2	2543113	6	79673788	C	A	SNP
358917	COMMD9	2543113	11	36280719	G	T	SNP
358996	LCE2C	4396053	1	152676238	C	A	SNP
359174	ODF3L1	3585049	15	75727327	C	A	SNP
```

Any ideas?

**Comment by njbernstein** [comment]
Thoughts?
